# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    # Step 3: Upgrade pip and install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        # Use pip to install from pyproject.toml
        pip install ./avinda_shamal

    # Step 4: Install Ruff for linting and formatting
    - name: Install the code linting and formatting tool Ruff
      run: pipx install ruff

    # Step 5: Lint code with Ruff
    - name: Lint code with Ruff
      run: |
        ruff check . --output-format=github --target-version=py39

    # Step 6: Check code formatting with Ruff
    - name: Check code formatting with Ruff
      run: |
        ruff format . --diff --target-version=py39
      continue-on-error: true

    # Step 7: Run tests with pytest
    - name: Test with pytest
      run: |
        pytest
